name: 'kubernetes-toolkit'
description: 'configures a kubernetes toolkit for your actions => Includes: kubectl, helm'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.kubectl_version }}
    - ${{ inputs.config }}
    - ${{ inputs.helm_version }}
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  kubectl_version:
    description: 'kubectl version, e.g. `v1.21.0`, defaults to latest'
    required: false
    default: latest
  config:
    description: 'kube config data'
    required: true
  helm_version:
    description: 'helm cli version, e.g. `v3.7.0`, defaults to latest. Not necessarily stable.'
    required: false
    default: latest
